"""init tables: users and api_keys

Revision ID: 7727a5323fb0
Revises: 
Create Date: 2025-08-08 20:13:29.402857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7727a5323fb0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_table(
        'apikeys',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('key_prefix', sa.String(length=32), nullable=False),
        sa.Column('hashed_key', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apikeys_created_at'), 'apikeys', ['created_at'], unique=False)
    op.create_index(op.f('ix_apikeys_key_prefix'), 'apikeys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_apikeys_user_id'), 'apikeys', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apikeys_user_id'), table_name='apikeys')
    op.drop_index(op.f('ix_apikeys_key_prefix'), table_name='apikeys')
    op.drop_index(op.f('ix_apikeys_created_at'), table_name='apikeys')
    op.drop_table('apikeys')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
